### ISSUE TITLE
Deploy RSCT daemonset as post-install customization

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-playbooks#26]
Instructions from Sebastien Chabrolles (@schabrolles )

Step 1: Create a project
```
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: powervm-rmc
```
Step2: Create powervm-rmc service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: powervm-rmc
  namespace: powervm-rmc
```
Step3: add privileged to powervm-rmc sa
```
oc adm policy add-scc-to-user -z powervm-rmc privileged -n powervm-rmc
```
Step4: deploy the daemonset
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: powervm-rmc
  namespace: powervm-rmc
spec:
  selector:
    matchLabels:
      app: powervm-rmc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: powervm-rmc
    spec:
      nodeSelector:
        kubernetes.io/arch: ppc64le
        node.openshift.io/os_id: rhcos
      restartPolicy: Always
      serviceAccountName: powervm-rmc
      hostNetwork: true
      containers:
        - name: powervm-rmc
          image: 'quay.io/powercloud/rsct-ppc64le:latest'
          ports:
            - name: rmc-tcp
              hostPort: 657
              containerPort: 657
              protocol: TCP
            - name: rmc-udp
              hostPort: 657
              containerPort: 657
              protocol: UDP
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
          securityContext:
            privileged: true
            runAsUser: 0
      serviceAccount: powervm-rmc
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
```
