### ISSUE TITLE
Configure Chrony during cores installation

### ISSUE THREAD

**Issue by schabrolles** [ocp-power-automation/ocp4-playbooks#31]
We were faced to issues when trying to install OCP on systems where firmware clock was not properly configured.

The issue was that the bastion/helper node (based on rhel) add chrony/ntp configured (which resync time) but cores node were not. 
All certificates generated by bastion cannot be used by nodes during installation (1h time difference).

We think it could be a good option to add the possibility to be able to specify the time-server to add to the coreos for chrony configuration.

Here is an example of the variables we can use to setup chrony.

```
chronyconfig:
  enabled: true
  content:
    - server: ntp1.example.com
      options: iburst
    - server: ntp2.example.com
      options: iburst
```

We can use `chronyconfig.enabled: false` as a default value

This PR is a First Step, as we also want to push a PR in the terraformproject ([ocp4-upi-powervm](https://github.com/ocp-power-automation/ocp4-upi-powervm)) in order to automate creation of OCP4 with chrony enabled.
